name: Test and Deploy
on:
    push:
    pull_request:
jobs:
    publish_pypi:
        runs-on: ubuntu-latest
        name: Publish to pypi
        needs: [test_linux, test_windows]
        if: github.ref =='refs/heads/master' && startsWith('v', github.event.head_commit.message) && endsWith('release', github.event.head_commit.message) && github.event_name!='pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Test
            - run: |
                  echo "success"
