name: Test and Deploy
on:
    push:
    pull_request:
jobs:
    test:
        runs-on: ubuntu-latest
        name: TestEcho
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Test
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
                  MESSAGE: ${{ github.event.head_commit.message }}
              run: |
                  echo "$GITHUB_CONTEXT"
                  echo "$MESSAGE"

    publish_pypi:
        runs-on: ubuntu-latest
        name: TestFInal
        # if: startsWith('v', github.event.head_commit.message)
        if: github.ref =='refs/heads/master' && startsWith('v', github.event.head_commit.message) && endsWith('release', github.event.head_commit.message) && github.event_name!='pull_request'
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Test
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: |
                  echo "$GITHUB_CONTEXT"
